### ISSUE TITLE
Pull French translation on Transifex

### ISSUE THREAD

**Issue by severinmenard** [hotosm/hot-exports#87]
I completed/improved my translation

**Comment by mataharimhairi** [comment]
@dodobas I am going to go through the issues and start categorizing them. I just wanted to check whether or not this one has been pushed?

**Comment by severinmenard** [comment]
Not yet, one month after... I am wondering why my edits need to be reviewed by someone that is not a French speaker. Seems I am the only one to have worked on the French version. Why my edits could not be automatically updated on the website?

**Comment by dodobas** [comment]
It's not possible to update translations automatically because all translations are translation sources are part of the git repository, so we need to add them to the repository before deploying to the server.

New translations have been added as commit 09ba9d3bf14b1d7f9c86e5820182ced69435d769
