### ISSUE TITLE
Generate a .obf file for OsmAnd

### ISSUE THREAD

**Issue by bgirardot** [hotosm/hot-exports#89]
It would really help if we also had the native OsmAnd file format. OsmAnd is used in the field as part of the MissingMaps project and an easy way for them to get updates of the areas they are mapping would be great.

**Comment by mataharimhairi** [comment]
@bgirardot I believe this is linked to issue #77 Add OSMAnd File Format

**Comment by bgirardot** [comment]
I am going to close this as it is a duplicate, thank you for pointing that out. But at the same time, I object to the "low priority" label placed on it and the original issue.
